services:
  car-rental-system-api:
    build:
      context: ./app
    depends_on:
      - car-rental-system-database
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 35729:35729
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  car-rental-system-database:
    image: mysql:8.2.0
    container_name: car-rental-system-mysql-db
    restart: unless-stopped
    #volumes: 
    #  - database:/data/db
    ports:
      - 33066:3306
