services:
  api:
    build:
      context: ./backend
    depends_on:
      - database
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync
    networks:
      - default

  database:
    image: mysql:8.2.0
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./db/script:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - api
    develop:
      watch:
        - path: ./src
          target: /usr/src/app/src
          action: sync
        - path: ./public
          target: /usr/src/app/public
          action: sync
    networks:
      - default

networks:
  default:
